Repository laterpay/supertab-docs, pull requests merged in 2025-05, with the labels that each got.

#6 feat: supertab js docs
  docs.json
  snippets/supertab-js/experiences-config-parameters.mdx
  supertab-integrate/tab-js.mdx
  supertab-js/experiences/starting-experiences.mdx
  supertab-js/installation.mdx
  supertab-js/introduction.mdx
  supertab-js/reference/api.mdx
  supertab-js/reference/auth.mdx
  supertab-js/reference/checkout.mdx
  supertab-js/reference/errors.mdx
  supertab-js/reference/overview.mdx
Labels: 5 min review

#7 CAPI / MAPI docs changes WIP
  customer-api/authentication.mdx
  customer-api/endpoints/purchase-a-one-time-offering.mdx
  customer-api/endpoints/retrieve-a-one-time-offering.mdx
  customer-api/openapi-2025-04-01.json
  customer-api/overview.mdx
  customer-api/versioning.mdx
  docs.json
  merchant-api/authentication.mdx
  merchant-api/openapi-2025-04-01.json
  merchant-api/overview.mdx
  merchant-api/versioning.mdx
  snippets/sdk-warning.mdx
  supertab-integrate/custom-integrations.mdx
  supertab-integrate/customer-api.mdx
  supertab-integrate/customer-api/authentication.mdx
  supertab-integrate/customer-api/clients.mdx
  supertab-integrate/customer-api/images/customerapi-js-relationship.png
  supertab-integrate/customer-api/introduction.mdx
  supertab-integrate/customer-api/payments.mdx
  supertab-integrate/customer-api/purchasing.mdx
  supertab-integrate/customer-api/versioning.mdx
Labels: 5 min review

#9 Adds documentation about consuming webhooks under the MAPI docs
  docs.json
  merchant-api/webhooks/consuming-webhooks.mdx
Labels: 1 min review

#10 Consolidates MAPI and CAPI docs under a single top level tab
  docs.json
Labels: non-code, 5 min review

#8 supertab.js guide edits
  supertab-js/experiences/guide.mdx
Labels: 1 min review, single-line

#12 SET-2969 Add scopes to endpoints
  customer-api/authentication.mdx
  customer-api/endpoints/purchase-a-one-time-offering.mdx
  customer-api/endpoints/purchase-an-offering.mdx
  customer-api/endpoints/retrieve-a-one-time-offering.mdx
  customer-api/endpoints/retrieve-a-purchase.mdx
  customer-api/endpoints/retrieve-customer.mdx
  customer-api/endpoints/retrieve-entitlement-status.mdx
  customer-api/endpoints/retrieve-site.mdx
  customer-api/endpoints/retrieve-the-current-customer.mdx
  customer-api/openapi-2025-04-01.json
  merchant-api/authentication.mdx
  merchant-api/endpoints/create-onetime-offering.mdx
  merchant-api/endpoints/retrieve-onetime-offering.mdx
  snippets/capi-read.mdx
  snippets/capi-write.mdx
  snippets/mapi-read.mdx
  snippets/mapi-write.mdx
Labels: 20 min review

#13 Update CAPI specs
  customer-api/openapi-2025-04-01.json
Labels: 5 min review, single-line

#14 Hacky fix for formatting
  snippets/capi-read.mdx
  snippets/capi-write.mdx
  snippets/mapi-read.mdx
  snippets/mapi-write.mdx
Labels: 1 min review
